-- Roofberries Cocktail Bar — QR table ordering
-- 0007_seed_category_images.sql: representative photo per category (the
-- first item photo in each), for categories that have any item photo.
-- Generated by scripts/generate-seed-sql.js.

update public.categories set image_url = 'https://d1hddaam55e99y.cloudfront.net/969_1000375275.png' where id = 'b06a0a6d-f6fa-46e7-b309-8b11d5911f38';
update public.categories set image_url = 'https://d1hddaam55e99y.cloudfront.net/969_1000685252.png' where id = '61991f7d-2f5b-4aaf-87e4-2b6aec945ac8';
update public.categories set image_url = 'https://d1hddaam55e99y.cloudfront.net/969_images%20-%202026-09-17T182700.466.png' where id = '8ec64254-99ee-470d-9daa-da6696480dc6';
update public.categories set image_url = 'https://d1hddaam55e99y.cloudfront.net/969_DSC05714.jpg' where id = 'e4f32ab0-8a0e-4aad-8510-d20b739dbbad';
update public.categories set image_url = 'https://d1hddaam55e99y.cloudfront.net/969_SSP-213_11zon.jpg' where id = '2dd89a2f-836f-4596-ad1e-f6a5b254a05c';
update public.categories set image_url = 'https://d1hddaam55e99y.cloudfront.net/969_1000373404.png' where id = '68477969-a840-487b-af6f-12e27c905570';
update public.categories set image_url = 'https://d1hddaam55e99y.cloudfront.net/969_DSC05940.jpg' where id = '3d57ed80-e754-4f9f-afc7-1f8f9d848080';
update public.categories set image_url = 'https://d1hddaam55e99y.cloudfront.net/969_1000681208.png' where id = 'e3ee082b-a31e-4672-827f-8155e47b4c3a';
update public.categories set image_url = 'https://d1hddaam55e99y.cloudfront.net/969_1000373376.png' where id = '436011f9-b803-4f48-9956-f5a55f1df334';
update public.categories set image_url = 'https://d1hddaam55e99y.cloudfront.net/969_SSP-031_11zon.jpg' where id = '5c8a104a-8010-4831-9057-63cedd52f5ff';
update public.categories set image_url = 'https://d1hddaam55e99y.cloudfront.net/969_SSP-055_11zon.jpg' where id = '9ae7f9ee-359b-4e9f-8696-071274b92560';
update public.categories set image_url = 'https://d1hddaam55e99y.cloudfront.net/969_DSC00407.jpg' where id = 'd466bb91-da09-4e3d-b82c-e144c4ad156f';
update public.categories set image_url = 'https://d1hddaam55e99y.cloudfront.net/969_SSP-061_11zon.jpg' where id = '84831bf6-1311-48e0-8659-74ff513a8764';
update public.categories set image_url = 'https://d1hddaam55e99y.cloudfront.net/969_1000553976.png' where id = '47aa2ac6-deb1-4daa-9359-2300bbf17a2a';
update public.categories set image_url = 'https://d1hddaam55e99y.cloudfront.net/969_1000553946.png' where id = '9e51b7ab-f51c-4806-a287-13e3eb77511c';
update public.categories set image_url = 'https://d1hddaam55e99y.cloudfront.net/969_1000553951.png' where id = '37b94b5b-0f79-47ec-baef-082327cc68e4';
update public.categories set image_url = 'https://d1hddaam55e99y.cloudfront.net/969_1000650799.png' where id = 'a937b14b-cdae-49e5-85e6-63a8d1eb597e';
update public.categories set image_url = 'https://d1hddaam55e99y.cloudfront.net/969_1000650800.webp' where id = 'a847d4ba-184c-4546-b2e5-9f24e4d744d5';
update public.categories set image_url = 'https://d1hddaam55e99y.cloudfront.net/969_1000210175.webp' where id = 'a28897f6-41b8-488c-b6de-b97a683ddfe4';
update public.categories set image_url = 'https://d1hddaam55e99y.cloudfront.net/969_1000210179.png' where id = 'c0adba7b-124b-43a8-aee7-71f114e0be22';
update public.categories set image_url = 'https://d1hddaam55e99y.cloudfront.net/969_1000210218.jpg' where id = '549f7ab4-90b7-4c67-a8e6-3229921c808d';
update public.categories set image_url = 'https://d1hddaam55e99y.cloudfront.net/969_1000650801.jpg' where id = '3910c485-5760-4abe-b437-f4173dd82622';
update public.categories set image_url = 'https://d1hddaam55e99y.cloudfront.net/969_1000210184.jpg' where id = '6b1fc030-78a3-42f6-8635-b66635391623';
update public.categories set image_url = 'https://d1hddaam55e99y.cloudfront.net/969_1000210257.webp' where id = '6934d404-7cca-4cc4-a797-de5d0a8813cf';
update public.categories set image_url = 'https://d1hddaam55e99y.cloudfront.net/969_1000210192.png' where id = '7c0ce2ba-dd70-46a1-83ff-9676d5668fa1';
update public.categories set image_url = 'https://d1hddaam55e99y.cloudfront.net/969_1000210237.jpg' where id = '2f070840-b983-4ba3-808f-7f161f2a401b';
update public.categories set image_url = 'https://d1hddaam55e99y.cloudfront.net/969_1000210251.jpg' where id = '737d9929-bafd-490a-b221-f1ce0da88968';
update public.categories set image_url = 'https://d1hddaam55e99y.cloudfront.net/969_1000210147.jpg' where id = 'd5241224-6769-4949-8ef5-d77b411f4c2a';
update public.categories set image_url = 'https://d1hddaam55e99y.cloudfront.net/969_1000210173.jpg' where id = 'e980995e-c76e-4344-8ac2-452c4c610cce';
update public.categories set image_url = 'https://d1hddaam55e99y.cloudfront.net/969_1000209942.jpg' where id = '7bccd15a-d266-4f0a-a4cd-f19b9c38027c';
update public.categories set image_url = 'https://d1hddaam55e99y.cloudfront.net/969_1000209973.jpg' where id = 'f4ba5b1f-a479-4697-8883-7e3778dff1c9';
update public.categories set image_url = 'https://d1hddaam55e99y.cloudfront.net/969_1000210112.webp' where id = '8e571a77-0a07-42f8-9736-d181983966a7';
update public.categories set image_url = 'https://d1hddaam55e99y.cloudfront.net/969_1000210127.png' where id = '36a92a3d-964e-43ec-b102-cac3e098d1dc';
